name: Build & Publish Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create variables
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build TV APK
        run: ./gradlew :tv:assembleRelease --info

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            **/*.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TIMESTAMP }}
          prerelease: true
          files: |
            **/*.apk